Add install and remove scripts

diff --git a/debian/freeradius-oauth2-perl.prerm b/debian/freeradius-oauth2-perl.prerm
--- a/debian/freeradius-oauth2-perl.prerm
+++ b/debian/freeradius-oauth2-perl.prerm
@@ -1,11 +1,23 @@
 #!/bin/sh
 set -e
 
+if [ -d /etc/freeradius/3.0 ]; then
+    RADDB_DIR=/etc/freeradius/3.0
+elif [ -d /etc/freeradius ]; then
+    RADDB_DIR=/etc/freeradius
+else
+    echo "ERROR: Could not find the FreeRADIUS configuration directory"
+    exit 2
+fi
+
 case "$1" in
     remove|upgrade|deconfigure)
-		rm -f /etc/freeradius/mods-enabled/oauth2 /etc/freeradius/3.0/mods-enabled/oauth2 \
-		      /etc/freeradius/mods-available/oauth2 /etc/freeradius/3.0/mods-available/oauth2 \
-			  /etc/freeradius/policy.d/oauth2 /etc/freeradius/3.0/policy.d/oauth2
+        rm -f ${RADDB_DIR}/mods-available/oauth2 \
+              ${RADDB_DIR}/mods-enabled/oauth2 \
+              ${RADDB_DIR}/policy.d/oauth2
+        temp=$(tempfile)
+        cp ${RADDB_DIR}/dictionary ${temp}
+        grep -v "INCLUDE /usr/share/freeradius-oauth2-perl/dictionary" ${temp} > ${RADDB_DIR}/dictionary
     ;;
 
     failed-upgrade)
