GitHub workflow refactor
- Add names
- Add check for whether the built .deb package matches the git tag
  before publishing
- Refactor steps into two jobs, one depending on the other

diff --git a/.github/workflows/debian.yml b/.github/workflows/debian.yml
--- a/.github/workflows/debian.yml
+++ b/.github/workflows/debian.yml
@@ -5,7 +5,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+        name: Source Checkout
       - uses: jtdor/build-deb-action@v1
+        name: Build Debian Packages
         id: build_step
         env:
           DEB_BUILD_OPTIONS: noautodbgsym
@@ -16,13 +18,24 @@ jobs:
         run: |
           echo "${{ steps.build_step.outputs.ARTIFACTS }}" | grep '\.deb$'
           echo "deb=$( echo "${{ steps.build_step.outputs.ARTIFACTS }}" | grep '\.deb$' )" >> "$GITHUB_OUTPUT"
-          ls -al
-          find debian/ 
+          echo "version=$( grep -m 1 '^freeradius-oauth2-perl ' debian/changelog | sed -e 's/.*(//' -e 's/).*//' )" >> "$GITHUB_OUTPUT"
+          echo "GITHUB_OUTPUT:"
+          cat "$GITHUB_OUTPUT" | sed -e 's/^/    /'
+
+  publish:
+    runs-on: ubuntu-latest
+    needs: build-debs
+    steps:
+      - name: Validate that the version matches the tag
+        if: github.ref_type == 'tag' && github.ref_name != steps.artifacts.outputs.version
+        run: |
+          echo "::error Debian package version ${{ steps.artifacts.outputs.version }} does not match tag ${{ github.ref_name }}"
+          exit 1
 
       - name: Upload package as a Release Asset
         # Use a community action to upload the artifact to the GitHub Release
         uses: softprops/action-gh-release@v2
-        if: github.ref_type == 'tag'
+        if: github.ref_type == 'tag' && github.ref_name == steps.artifacts.outputs.version
         with:
           files: |
             ${{ steps.artifacts.outputs.deb }}
